### ISSUE TITLE
Pierre is not funny

### ISSUE THREAD

**Issue by NicolasHusser** [NicolasHusser/javascript-project#1]
I don't want this guy in my group

**Comment by PaulineIsComing** [comment]
- Anfang : String Spielregel / Menu (Regel - Spielen - High Score anrufen- Pseudo new ändern)
- Spiel : Kartebauen anrufen / While « Insel nicht gut » (Spiel)  
                                                  -> A oder B / Button zur Bestätigung / aktueller Insel 
- Ende : Menu (gespielte Seekarte - Leistung - High Score anrufen)
- High Score
- Karte (bauen und schauen)
